title: Portfolio 
author: Audrey Yee
email: kyee4636@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is the site to fill in my projects that i have done with data analytics and ux design 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
